### ISSUE TITLE
help me to solve this problem

### ISSUE THREAD

**Issue by vietthang25** [ruromgar/lisa_coco_converter#2]
Traceback (most recent call last):
  File "csv_data_to_json.py", line 211, in <module>
    main()
  File "csv_data_to_json.py", line 182, in main
    training_categories = get_categories(training=True)
  File "csv_data_to_json.py", line 108, in get_categories
    print('Tags len is: ' + str(len(tags)))
TypeError: object of type 'NoneType' has no len()

**Comment by ruromgar** [comment]
hey @vietthang2502, that means you don't have any tags. It's saying the `tags` object is None, and thus is has no length.

**Comment by vietthang25** [comment]
and how to solve this bug
![Screenshot from 2023-02-21 15-53-04](https://user-images.githubusercontent.com/77373839/220295676-c090dbc4-7fa5-48a5-b8fe-6e12c1589431.png)

**Comment by vietthang25** [comment]
i see the data in annotation json file is not sorting
Will that have any effect?
![Screenshot from 2023-02-21 16-14-30](https://user-images.githubusercontent.com/77373839/220301326-49a3e87a-808c-4f04-b9bd-2cfd7d4cb5bc.png)

**Comment by ruromgar** [comment]
> and how to solve this bug ![Screenshot from 2023-02-21 15-53-04](https://user-images.githubusercontent.com/77373839/220295676-c090dbc4-7fa5-48a5-b8fe-6e12c1589431.png)

This is failing because the list comprehension is empty. Looks like you don't have any image in your list that ends with that filename.

**Comment by ruromgar** [comment]
> i see the data in annotation json file is not sorting Will that have any effect? ![Screenshot from 2023-02-21 16-14-30](https://user-images.githubusercontent.com/77373839/220301326-49a3e87a-808c-4f04-b9bd-2cfd7d4cb5bc.png)

Hmmm no that shouldn't matter

**Comment by vietthang25** [comment]
thanks for your help !

**Comment by vietthang25** [comment]
@ruromgar
i want to convert all of dataset (include nightTrain,.....)
and when i run it, this bug happend 
how to solve it 
![image](https://user-images.githubusercontent.com/77373839/220810727-a260813c-0188-4b03-ae2d-af20ddc8d2dd.png)

**Comment by vietthang25** [comment]
i have solved it
thank you
