### ISSUE TITLE
Bug: Annotation tag returns NoneType

### ISSUE THREAD

**Issue by denguir** [ruromgar/lisa_coco_converter#3]
Hello, 
thanks for the data conversion script, very useful !

I found a little bug [here](https://github.com/ruromgar/lisa_coco_converter/blob/459505540618b6210c9c17f8878cca8b0c227a00/csv_data_to_json.py#L107) while using it. 
` ` ` python
tags = df['Annotation tag'].unique().tolist().sort()
` ` ` 
The sort() method returns None, I would suggest to use sorted builtin function instead. I will create a PR for that if you wish.

**Comment by ruromgar** [comment]
You're right, thanks for the PR! I've approved and merged :pray: 

Glad it was useful for you! :)
